#!/usr/bin/env python
# -*- coding: utf-8 -*-

#
# Copyright (c) 2022 Maksim Perov <coder@frtk.ru>
#

import subprocess

MIN = 1024*1024*1024

command=list()
command.append("lsof")
command.append("-N")

lsof = subprocess.Popen(command, stdout = subprocess.PIPE, stderr = subprocess.PIPE)
try:
    output, errs = lsof.communicate()
except:
    lsof.kill()

if (output):
    lst = str(output).split('\\n')
    deleted = []
    for l in lst:
        if 'deleted' in l:
            deleted.append(l)
    size = lambda s: s.split()[6]
    result = []
    for i in deleted:
        if size(i).isdecimal() and int(size(i)) > MIN:
            result.append(i)
    srtd = []
    srtd = sorted(result, key=lambda d: int(size(d)) if size(d).isdecimal() else 0, reverse=True)
    if srtd != []:
        print("\n".join(srtd))
